### PR TITLE
Guzzle 6 Support

### PR DESCRIPTION
**Pull request by aglipanci**

### CODE REVIEW

**Comment by aglipanci** [comment]
Pull Request also valid for #6

**Comment by tblanchard** [comment]
Thank you SO MUCH for doing this!  Just saved my day.

**Comment by aditya-cherukuri** [comment]
eagerly waiting for this to be merged and released

**Comment by quickshiftin** [comment]
Hi, I wrote this some time ago and have not given it much attention in the meantime. Thank you for your contribution!

**Comment by aglipanci** [comment]
Hey I totally understand that :) I have written a new PHP API client for Postmates but I started with yours and noticed that others use it too so I am just trying to help :) Keep up the great work!

**Pull request merged**
